### ISSUE TITLE
Scene and Traffic detection

### ISSUE THREAD

**Issue by CarpeDiemRo** [robmarkcole/HASS-Deepstack-scene#6]
Hi Rob, I'm using HA and I successfully integrated Scene, Face and Object detection. 

Now, I had a hard time trying to figure out how to use this:

```
sudo docker run -e VISION-TRAFFIC=True  -e VISION-DETECTION=True -v localstorage:/datastore \
-p 80:5000 deepquestai/deepstack
```
My configuration.yaml looks like
```
  - platform: deepstack_scene
    ip_address: 10.1.2.1
    port: 8081
    api_key: xxxxxx-xxxxx-xxxxx-xxxxx-89f1f221d0ed
    source:
      - entity_id: camera.deepstack_car_xxxxx
        name: 05 Car Street
```
I'm trying to identify accidents using this test image
![test-image4](https://user-images.githubusercontent.com/38489167/103567978-63873680-4ecd-11eb-8f98-2eb1642b3cac.jpg)
 
but every time when I run `image_processing.scan` returns streets which is true from scene detection but false from traffic perspective. 

HA log

```
Logger: pyhik.hikvision
Source: /usr/local/lib/python3.8/site-packages/pyhik/hikvision.py:300
First occurred: 20:54:17 (1 occurrences)
Last logged: 20:54:17
Sensor type "vehicledetection" is unsupported.
```

Can you give a bit of advice in order to achieve the correct result?

I'm running CPU Deepstack version on an Intel Server without GPU support. 

Thanks a lot.
